
DROP DATABASE IF EXISTS dars_20;
CREATE DATABASE dars_20;
USE dars_20;


CREATE TABLE Cars(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price BIGINT NOT NULL,
    start_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE Customers(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL, 
    start_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE Orders(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    cars_id BIGINT UNSIGNED NOT NULL, --
    customer_id BIGINT UNSIGNED NOT NULL, 
    quantity BIGINT NOT NULL,
    month INT NOT NULL CHECK (month <= 12),
    start_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    end_time DATETIME DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE Payments(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    order_id BIGINT UNSIGNED NOT NULL,
    price BIGINT NOT NULL,
    month INT NOT NULL,
    start_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE Payments
    ADD CONSTRAINT payments_order_id_foreign FOREIGN KEY (order_id) REFERENCES Orders(id);

ALTER TABLE Orders
    ADD CONSTRAINT orders_cars_id_foreign FOREIGN KEY (cars_id) REFERENCES Cars(id);

ALTER TABLE Orders
    ADD CONSTRAINT orders_customer_id_foreign FOREIGN KEY (customer_id) REFERENCES Customers(id);
